# Generated by Django 4.1.5 on 2023-01-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medarbejder",
            name="klasser",
            field=models.ManyToManyField(to="skole.klasse"),
        ),
    ]
