# Generated by Django 4.1.5 on 2023-01-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0002_medarbejder_klasser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klasse",
            options={"verbose_name": "pizza", "verbose_name_plural": "stories"},
        ),
    ]
