# Generated by Django 4.1.5 on 2023-01-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0003_alter_klasse_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="klasse",
            options={"verbose_name": "klasse", "verbose_name_plural": "klasser"},
        ),
    ]
