# Generated by Django 4.1.5 on 2023-01-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skole", "0004_alter_klasse_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="afdeling",
            options={"verbose_name": "afdeling", "verbose_name_plural": "afdelinger"},
        ),
    ]
